export type DefaultCategoryCatalogItem = {
  name: string;
  iconName: string;
  color: string;
  subcategories: string[];
};

export const DEFAULT_CATEGORY_CATALOG: DefaultCategoryCatalogItem[] = [
  {
    name: "Groceries",
    iconName: "ShoppingCart",
    color: "#22C55E",
    subcategories: [
      "Fruits & vegetables",
      "Meat",
      "Fish & seafood",
      "Dairy",
      "Eggs",
      "Bread & bakery",
      "Pasta, rice & grains",
      "Canned & packaged food",
      "Frozen foods",
      "Snacks",
      "Sweets & desserts",
      "Beverages",
      "Water",
      "Coffee & tea",
      "Spices & condiments",
      "Cooking ingredients",
      "Breakfast foods",
      "Baby food",
      "Household consumables",
      "Cleaning supplies",
      "Personal care",
      "Pet food",
    ],
  },
  {
    name: "Dining & Takeout",
    iconName: "Utensils",
    color: "#F97316",
    subcategories: [
      "Restaurant",
      "Fast food",
      "Café",
      "Bakery / pastry shop",
      "Food delivery",
      "Takeout",
      "Dessert / ice cream",
      "Bar / pub",
    ],
  },
  {
    name: "Transport",
    iconName: "Car",
    color: "#3B82F6",
    subcategories: [
      "Public transport",
      "Taxi / rideshare",
      "Fuel",
      "Parking",
      "Tolls",
      "Car maintenance",
      "Car wash",
      "Car insurance",
      "Vehicle registration / inspection",
      "Train",
      "Bus / coach",
      "Flights",
      "Bike / scooter",
    ],
  },
  {
    name: "Housing / Home",
    iconName: "House",
    color: "#A78BFA",
    subcategories: [
      "Rent",
      "Mortgage",
      "Utilities",
      "Electricity",
      "Gas",
      "Water",
      "Internet",
      "Mobile plan",
      "Home maintenance",
      "Repairs",
      "Furniture",
      "Home decor",
      "Appliances",
      "Renters / home insurance",
    ],
  },
  {
    name: "Bills & Utilities",
    iconName: "Zap",
    color: "#14B8A6",
    subcategories: [
      "Electricity",
      "Gas",
      "Water",
      "Heating",
      "Internet",
      "Mobile phone",
      "TV / streaming bundle",
      "Waste / sanitation",
      "HOA / maintenance fees",
    ],
  },
  {
    name: "Health & Medical",
    iconName: "Stethoscope",
    color: "#EF4444",
    subcategories: [
      "Pharmacy",
      "Doctor visit",
      "Dental",
      "Glasses / vision",
      "Supplements",
      "Medical tests",
      "Health insurance",
      "Therapy / counseling",
      "Personal medical devices",
    ],
  },
  {
    name: "Personal Care & Beauty",
    iconName: "Sparkles",
    color: "#EC4899",
    subcategories: [
      "Toiletries",
      "Skincare",
      "Haircare",
      "Cosmetics",
      "Grooming",
      "Barber / salon",
      "Hygiene products",
      "Wellness",
    ],
  },
  {
    name: "Shopping",
    iconName: "ShoppingBag",
    color: "#0EA5E9",
    subcategories: [
      "Clothing",
      "Shoes",
      "Accessories",
      "Bags / wallets",
      "Jewelry",
      "Electronics",
      "Phone accessories",
      "Computer accessories",
      "Books",
      "Stationery",
      "Gifts",
      "Hobby supplies",
    ],
  },
  {
    name: "Entertainment",
    iconName: "Film",
    color: "#8B5CF6",
    subcategories: [
      "Movies / cinema",
      "Games",
      "Music",
      "Events",
      "Subscriptions",
      "Sports events",
      "Hobbies",
      "Streaming",
      "Nightlife",
    ],
  },
  {
    name: "Education",
    iconName: "GraduationCap",
    color: "#10B981",
    subcategories: [
      "Tuition",
      "Courses",
      "Books",
      "School supplies",
      "Software / learning tools",
      "Exams / certifications",
      "Printing / copying",
    ],
  },
  {
    name: "Work / Business",
    iconName: "BriefcaseBusiness",
    color: "#6B7280",
    subcategories: [
      "Office supplies",
      "Software",
      "Equipment",
      "Travel",
      "Client meals",
      "Professional services",
      "Hosting / domains",
      "Ads / marketing",
    ],
  },
  {
    name: "Financial",
    iconName: "Banknote",
    color: "#06B6D4",
    subcategories: [
      "Bank fee",
      "Loan payment",
      "Credit card payment",
      "Interest",
      "Transfer fee",
      "Savings contribution",
      "Investment",
      "Tax",
      "Currency exchange",
    ],
  },
  {
    name: "Travel",
    iconName: "Plane",
    color: "#6366F1",
    subcategories: [
      "Accommodation",
      "Flights",
      "Train",
      "Local transport",
      "Food while traveling",
      "Travel insurance",
      "Activities",
      "Luggage / travel accessories",
    ],
  },
  {
    name: "Family & Kids",
    iconName: "Baby",
    color: "#F59E0B",
    subcategories: [
      "Baby products",
      "School items",
      "Toys",
      "Childcare",
      "Kids clothing",
      "Baby food",
    ],
  },
  {
    name: "Pets",
    iconName: "PawPrint",
    color: "#84CC16",
    subcategories: [
      "Pet food",
      "Vet",
      "Grooming",
      "Accessories",
      "Medicine",
    ],
  },
  {
    name: "Other",
    iconName: "CircleHelp",
    color: "#94A3B8",
    subcategories: [
      "Miscellaneous",
      "Unclassified",
      "Temporary review",
    ],
  },
];

export const DEFAULT_CATEGORY_SUBCATEGORIES: Record<string, string[]> =
  Object.fromEntries(
    DEFAULT_CATEGORY_CATALOG.map((item) => [item.name, item.subcategories]),
  );
